source 'https://github.com/CocoaPods/Specs.git'

target 'SPXKeychain_Example', :exclusive => true do
  pod "SPXKeychain", :path => "../"
end

target 'SPXKeychain_Tests', :exclusive => true do
  pod "SPXKeychain", :path => "../"

  pod 'Kiwi'
end
